This project includes the following third-party software:

== Static site generation

- Antora (Mozilla Public License Version 2.0)
  Copyright (c) 2017-present OpenDevise Inc. and the Antora Project Contributors
  https://gitlab.com/antora/antora/-/tree/main

- Antora Default UI (Mozilla Public License Version 2.0)
  Copyright (c) 2017-present OpenDevise Inc. and the Antora Project Contributors
  https://gitlab.com/antora/antora-ui-default

- @antora/lunr-extension (Mozilla Public License Version 2.0)
  Copyright (c) 2017-present OpenDevise Inc. and the Antora Project Contributors
  https://gitlab.com/antora/antora-lunr-extension

== Document conversion and processing

- Asciidoctor Project (MIT License)
  Copyright (C) 2014-present OpenDevise Inc. and the Asciidoctor Project
  https://github.com/asciidoctor/asciidoctor-pdf

- asciidoctor-diagram (MIT License)
  Copyright (c) 2014 Pepijn Van Eeckhoudt
  https://github.com/asciidoctor/asciidoctor-diagram

- asciidoctor-kroki (MIT License)
  Copyright (c) Asciidoctor Kroki contributors
  https://github.com/asciidoctor/asciidoctor-kroki

- asciidoctor-plantuml (MIT License)
  Copyright (c) 2017-present Guillaume Grossetie
  https://github.com/ggrossetie/asciidoctor-plantuml

== PDF generation

- Prawn (Dual License: GPL v2/v3 OR liberal terms)
  Copyright Gregory Brown and community contributions
  Used under liberal terms (not GPL)
  https://github.com/prawnpdf/prawn

- HexaPDF (MIT License)
  Copyright (c) 2015-2025 Thomas Leitner
  https://github.com/gettalong/hexapdf

== Diagram rendering and visualization

- Kroki (MIT License)
  Copyright (c) 2020-present Kroki
  https://github.com/yuzutech/kroki/tree/main

- Graphviz (Eclipse Public License 1.0)
  Copyright (c) 2000-2023 Graphviz Contributors
  https://github.com/ioquatix/graphviz

== Runtime and build tooling (Ruby / Node.js / Python)

- RubyGems (MIT License)
  Copyright (c) Chad Fowler, Rich Kilmer, Jim Weirich and others
  https://github.com/ruby/rubygems/blob/master/LICENSE.txt

- pg (BSD-2-Clause License)
  Copyright (c) 1997-2023 PostgreSQL Global Development Group
  https://github.com/ged/ruby-pg

- rubyzip (BSD-2-Clause License)
  Copyright (c) 2002-2004 Thomas Sondergaard
  https://github.com/rubyzip/rubyzip

- Opal (MIT License)
  Copyright (c) 2013-2023 Elia Schito and contributors
  https://github.com/opal/opal

- Puppeteer (Apache License 2.0)
  Copyright (c) 2017 Google Inc.
  https://github.com/puppeteer/puppeteer

- xml2js (MIT License)
  Copyright (c) 2010-2020 Maciej Urbański
  https://github.com/Leonidas-from-XIV/node-xml2js

- Python (Python Software Foundation License Version 2)
  Copyright (c) 2001-present Python Software Foundation
  https://github.com/python/cpython

- PyYAML (MIT License)
  Copyright (c) 2017-2021 Ingy dot Net; 2006-2016 Kirill Simonov
  https://github.com/yaml/pyyaml

== UI assets

- highlight.js (BSD 3-Clause License)
  Copyright (c) Highlight.js contributors
  https://github.com/highlightjs/highlight.js

- Octicons (MIT License)
  Copyright (c) GitHub
  https://github.com/primer/octicons

== Fonts

- Roboto font (Apache License 2.0)
  Copyright (c) Google
  https://github.com/googlefonts/roboto

- Times New Roman font files
  These font files may be subject to proprietary licensing. If you redistribute this repository or its artifacts, ensure you have the necessary rights to distribute these fonts.

== Optional LLM tooling and models

- Hermes Agent (MIT License)
  Copyright (c) 2025 Nous Research
  https://github.com/NousResearch/hermes-agent

- Ollama (MIT License)
  Copyright (c) 2023-present Ollama AI Inc.
  https://github.com/ollama/ollama

- gpt-oss:20b model (Apache License 2.0)
  Copyright (c) 2024-present GPT-OSS contributors
  Available through Ollama: ollama pull gpt-oss:20b

- Gemma3 4B model (Gemma Terms of Use)
  Copyright (c) 2024-present Google LLC
  Available through Ollama: ollama pull gemma3:4b

- Gemma model (Gemma Terms of Use)
  Copyright (c) 2024-present Google LLC
  Available through Ollama: ollama pull gemma:latest

- Mistral 7B model (Apache License 2.0)
  Copyright (c) 2023-present Mistral AI
  Available through Ollama: ollama pull mistral:7b

- Qwen2.5 model (Tongyi Qianwen License)
  Copyright (c) 2024-present Alibaba Cloud
  Available through Ollama: ollama pull qwen2.5:latest