= ODS - Open Documentation Standard
:title-page:
:toc: left
:toclevels: 2
:sectnums:
:icons: font
:source-highlighter: rouge
:imagesdir: .

== Быстрый старт

ODS использует два независимых процесса:

. Сборка документации — генерация AsciiDoc файлов и PDF из различных источников.
. Сборка сайта — создание HTML сайта из готовых AsciiDoc файлов.

=== Установка зависимостей

[source,bash]
----
# Docker (рекомендуется)
docker --version

# Или локальная установка:

# Ruby 3.2+ и гемы
gem install asciidoctor asciidoctor-pdf asciidoctor-kroki prawn pg graphviz hexapdf

# Node.js 20+ зависимости
npm install

# Antora (устанавливается локально через npm - рекомендуется)
npm install @antora/cli @antora/site-generator-default

# Antora (устанавливается глобально через npm)
npm install -g @antora/cli @antora/site-generator-default


# PlantUML (для генерации SVG диаграмм)
# Установите PlantUML и Java

# Graphviz (для ERD диаграмм)
# Установите Graphviz

# PostgreSQL (для документации БД)
# Настройте подключение в config.yml
----

=== Сборка документации

[source,bash]
----
# С помощью Docker (рекомендуется)
cd docker/docs-ruby
./build.sh

# Или локально:
ruby tools/start.rb
----

=== Сборка сайта документации

[source,bash]
----
# Запуск сайта из npx
npx antora antora-playbook.yml

# Или если Antora установлена глобально:
antora antora-playbook.yml
----

== Полная документация

Для получения подробной информации о проекте ODS, включая:

* Детальную архитектуру проекта
* Конфигурацию компонентов
* Процесс сборки и автоматизации
* Интеграцию с CI/CD
* Технологический стек
* Кастомные PDF конвертеры
* Примеры использования

Обратитесь к полной документации: link:components/project-guide/modules/ROOT/pages/index.adoc[Руководство по документированию]

== Ссылки

* https://vvvnik.gitlab.io/my-project/data-processing-engine/1/index.html[Наш сайт документации]
* https://docs.antora.org/[Документация Antora]
* https://asciidoctor.org/[Документация AsciiDoc]
* https://plantuml.com/[PlantUML для SVG диаграмм]
* https://graphviz.org/[Graphviz для ERD диаграмм]
* https://docs.docker.com/[Документация Docker]
* https://docs.gitlab.com/ee/ci/[GitLab CI/CD]