version: '3.8'

services:
  # Генерация PDF документов
  pdf:
    image: registry.gitlab.com/vvvnik/ods-project/ruby-node-antora:1
    container_name: ods-project-pdf
    volumes:
      - .:/app
    working_dir: /app
    command: ruby tools/start.rb

  # Сборка сайта с Antora
  site:
    image: registry.gitlab.com/vvvnik/ods-project/ruby-node-antora:1
    container_name: ods-project-site
    volumes:
      - .:/app
    working_dir: /app
    command: antora antora-playbook.yml
