:doctype: book
include::../partials/attr_common.adoc[]

= Сервис аэропортов
:title-page:
:custom_title_page: original
:custom_other_page: none
:code-main: AIRPORT
:data_report: {localdate}
:name_doc: Сервис аэропортов
:number_doc: 1
:name_prog_main: Сервис аэропортов
:name-prog: Сервис
:tom: 1
:imagesdir: ../images
:docinfo: shared
:!chapter-signifier:
:!section-refsig:
:table-caption!:
:section-refsig: разделе
:toc: macro
:toc-title: Содержание 
:sectnumlevels: 7
:toclevels: 4

== Назначение документа

Документ содержит описание сервиса аэропортов, включая схему базы данных, структуру таблиц и логические связи между сущностями системы управления аэропортами.

== Демонстрация автоматической генерации документации

=== О системе парсинга БД

Данный компонент демонстрирует возможности автоматической генерации документации из базы данных PostgreSQL. Система поддерживает подключение к любым базам данных и автоматически создает:

* ERD диаграммы (Entity Relationship Diagrams)
* Логические диаграммы базы данных
* Подробное описание всех таблиц и их связей
* Документацию по индексам и ограничениям

=== Процесс генерации документации

Документация генерируется в несколько этапов:

==== Подключение к БД
Система подключается к PostgreSQL используя настройки из `database.yml`:
+
[source,yaml]
----
host: localhost
port: 5432
database: airport_db
username: postgres
password: password
----

==== Анализ схемы
Автоматически извлекается информация о:
* Таблицах и их структуре
* Связях между таблицами (foreign keys)
* Индексах и ограничениях
* Типах данных и размерах полей

==== Генерация диаграмм
Создаются SVG диаграммы с помощью Graphviz:
* ERD диаграмма (физическая модель)
* Логическая диаграмма (концептуальная модель)

==== Создание документации
Генерируется AsciiDoc документация с:
* Описанием всех таблиц
* Детализацией полей и их типов
* Схемами связей между таблицами

== Общее описание

=== Назначение сервиса

Сервис аэропортов предназначен для управления данными аэропортов, воздушных судов, рейсов, бронирований и билетов.

Основные функции:

* Управление информацией об аэропортах;
* Управление данными воздушных судов;
* Планирование и управление рейсами;
* Система бронирования билетов;
* Управление посадочными талонами.

=== Архитектура данных

Система построена на основе реляционной модели данных с четкой структурой связей между сущностями.

Основные сущности:

* Аэропорты и их данные;
* Воздушные суда и их характеристики;
* Рейсы и маршруты;
* Бронирования и билеты;
* Посадочные талоны.

== Схема данных

=== Обзор схемы базы данных

include::../partials/docs-db/schemas_index.adoc[]

== Диаграммы

=== ERD диаграмма базы данных

:num_i: {counter:figure-number}

ERD диаграмма базы данных представлена на <<id_i_{num_i}, Рисунке {num_i}>>.

[.landscape]
<<<<

[#id_i_{num_i}]
.Рисунок {num_i}. ERD диаграмма базы данных
// image::images-db/erd_bookings.svg[width=100%, height=500px, pdfwidth=100%, scaledwidth=100%]

[plantuml, erd-bookings]
----
include::../partials/docs-db/erd_bookings.puml[plantuml, erd-bookings]
----
[.portrait]
<<<<

=== Логическая диаграмма

:num_i: {counter:figure-number}

Логическая диаграмма базы данных представлена на <<id_i_{num_i}, Рисунке {num_i}>>.

[.landscape]
<<<<

[#id_i_{num_i}]
.Рисунок {num_i}. Логическая диаграмма базы данных
// image::images-db/logical_bookings.svg[width=100%, height=500px, pdfwidth=100%, scaledwidth=100%]

[plantuml, logical_bookings]
----
include::../partials/docs-db/logical_bookings.puml[plantuml, logical-bookings]
----
[.portrait]
<<<<

=== Детальная логическая схема

include::../partials/docs-db/bookings_logical.adoc[]

== Описание таблиц

include::../partials/docs-db/bookings_tables.adoc[] 

== Заключение

Сервис аэропортов обеспечивает комплексное управление данными авиационной системы, включая аэропорты, воздушные суда, рейсы и бронирования. Структурированная схема данных гарантирует целостность и эффективность работы системы.

=== Демонстрация возможностей системы

Данный компонент наглядно демонстрирует возможности автоматической генерации документации из базы данных:

* **Автоматический парсинг** - система автоматически извлекает структуру БД
* **Генерация диаграмм** - создаются профессиональные ERD и логические диаграммы
* **Документирование таблиц** - подробное описание всех полей и связей
* **Поддержка любых БД** - система работает с PostgreSQL, MySQL, Oracle и другими
* **Интеграция с CI/CD** - документация обновляется автоматически при изменениях в БД

Система парсинга БД позволяет быстро создавать актуальную техническую документацию для любых проектов, экономя время разработчиков и обеспечивая высокое качество документации.
