include::../partials/attr_common.adoc[] 
:doctype: book
:title-page:
:custom_title_page: original
:custom_other_page: none
:toc: macro
:toc-title: Содержание
:toclevels: 2
:sectnums:
:!chapter-signifier:
:!section-refsig:
:figure-caption!:
:imagesdir: ../images
:table-caption!: 
:section-refsig: разделе
:chapter-refsig: разделе
:sectnums!:

= Актуальная документация – там же где код

Пока документация в Confluence, EvaWiki, Word и чатах – новый разработчик теряет месяц. Андрей в отпуске, актуальное в личке, структуры нет. Повторяется с каждым новым человеком в команде.

:note-caption: Стоимость:
****
[NOTE]
от *400 000* до *700 000* рублей
****

Код открытый – можете поднять сами. Мы для тех кто считает время команды.

Разобрать под ваш стек: https://t.me/VladimirNikTelegram[@VladimirNikTelegram] (Telegram).

== Вот где обычно останавливаются:

CI/CD для документации падает в бэклог – и остаётся там потому что не блокирует релиз

Диаграммы устаревают раньше чем выходит фича

Каждый пишет в своём инструменте – само не починится

ODS – конвейер который через это прошёл. Не проектируете архитектуру с нуля – настраиваете готовую.

== Поехали!
Для перехода к документации перейдите по ссылке: xref:Руководство_по_документированию.adoc[Руководство по документированию].